### ISSUE TITLE
Compatibility with Unity 2019

### ISSUE THREAD

**Issue by BeatriceThalo** [campfireunion/VRKeys#18]
Hoping you can help with upgrading this asset and/or listing the required steps, thanks!

Dependency changes:
"Oculus Utilities for Unity" is now included in "Oculus Integration" asset.
SteamVR has upgraded to 2.x
Text Mesh Pro is now a Unity package.

Steps I've taken so far after importing VRKeys into my 2019 project:
1) Downloaded deprecated [SteamVR Plugin 1.2.3](https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3) and imported the package, saying no thanks to Unity auto-fixing the APIs, and renaming anything VR.VR* -like in Steam's scripts as XR.XR*
2) The keyboard's game object children "Label"s are missing their script references, I'm not sure what the references should be.

**Comment by lux** [comment]
We've been slow at updating this for 2019 since our main project we use it in was still on 2017.3. We're just about to get updated in the next couple weeks though, which I'm really looking forward to so we can remove all platform-specific dependencies.

I'm going to try loading VRKeys on its own in 2019 today and see if I can get that part done sooner for you.

**Comment by BeatriceThalo** [comment]
Brilliant, thank you!

**Comment by lux** [comment]
Had some time today after all and got it working! Was a good chance to familiarize myself with Unity's new XR APIs :)

I haven't tested the export yet, but I believe you should be able to import and run the demo scene. Let me know if you run into any problems.
